"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sequelize = exports.Report = exports.Pet = exports.Auth = exports.User = void 0;
const sequalize_1 = require("../lib/sequalize");
Object.defineProperty(exports, "sequelize", { enumerable: true, get: function () { return sequalize_1.sequelize; } });
const users_js_1 = require("./users.js");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return users_js_1.User; } });
const auth_js_1 = require("./auth.js");
Object.defineProperty(exports, "Auth", { enumerable: true, get: function () { return auth_js_1.Auth; } });
const pet_js_1 = require("./pet.js");
Object.defineProperty(exports, "Pet", { enumerable: true, get: function () { return pet_js_1.Pet; } });
const report_js_1 = require("./report.js");
Object.defineProperty(exports, "Report", { enumerable: true, get: function () { return report_js_1.Report; } });
users_js_1.User.hasOne(auth_js_1.Auth, { foreignKey: "userId" });
auth_js_1.Auth.belongsTo(users_js_1.User, { foreignKey: "userId" });
users_js_1.User.hasMany(pet_js_1.Pet, { foreignKey: "userId" });
pet_js_1.Pet.belongsTo(users_js_1.User, { foreignKey: "userId" });
pet_js_1.Pet.hasMany(report_js_1.Report, { foreignKey: "petId" });
report_js_1.Report.belongsTo(pet_js_1.Pet, { foreignKey: "petId" });
